#!/usr/bin/env bash
# _config.sh - Three-tier configuration for claude-git-workflow scripts
# Usage: sourced automatically by _common.sh -- do not source directly
#
# Resolution order (highest to lowest priority):
#   1. Environment variables (CGW_*)       -- CI/automation overrides
#   2. Config file ($PROJECT_ROOT/.cgw.conf) -- generated by configure.sh
#   3. Built-in defaults                   -- works without any config
#
# All scripts work out of the box with defaults. Run configure.sh once
# to auto-detect your project's settings and generate .cgw.conf.

# ============================================================================
# PROJECT ROOT AUTO-DETECTION
# ============================================================================
# Walk up from SCRIPT_DIR to find the nearest .git/ directory.
# Works regardless of where scripts/ lives in the project tree.

_detect_project_root() {
  local dir
  dir="$(cd "${SCRIPT_DIR}" && pwd)"
  while [[ "${dir}" != "/" ]] && [[ -n "${dir}" ]]; do
    if [[ -d "${dir}/.git" ]]; then
      echo "${dir}"
      return 0
    fi
    dir="$(dirname "${dir}")"
  done
  # Fallback: ask git directly
  if git rev-parse --show-toplevel 2>/dev/null; then
    return 0
  fi
  echo "[ERROR] Cannot find git repository root from ${SCRIPT_DIR}" >&2
  return 1
}

# Allow tests (and CI overrides) to pin PROJECT_ROOT via env var, skipping auto-detection.
if [[ -z "${PROJECT_ROOT:-}" ]]; then
  PROJECT_ROOT="$(_detect_project_root)" || exit 1
fi

# ============================================================================
# CONFIG FILE LOADING
# ============================================================================
# Source .cgw.conf if it exists. Variables already set in the environment
# (env vars take priority) are NOT overwritten because bash ${VAR:-} syntax
# checks for unset-or-empty, but env vars that ARE set skip the defaults block.
# We achieve true "env wins" by only sourcing variables the env hasn't set yet.

_CGW_CONF="${PROJECT_ROOT}/.cgw.conf"

if [[ -f "${_CGW_CONF}" ]]; then
  # Read .cgw.conf line-by-line, only applying variables not already set in the environment.
  # This ensures env vars take priority AND derived values (e.g. CGW_PROTECTED_BRANCHES
  # referencing CGW_TARGET_BRANCH) stay consistent with the values actually used.
  while IFS= read -r _line; do
    [[ "${_line}" =~ ^[[:space:]]*# ]] && continue # skip comments
    [[ "${_line}" =~ ^[[:space:]]*$ ]] && continue # skip blank lines
    # Only accept CGW_* assignment lines (optionally prefixed with export).
    # Reject anything else to prevent eval of arbitrary shell statements.
    if [[ "${_line}" =~ ^[[:space:]]*(export[[:space:]]+)?(CGW_[A-Z0-9_]+)= ]]; then
      _cgw_var="${BASH_REMATCH[2]}"
      # Only set if not already in environment (preserves env var priority)
      if [[ -z "${!_cgw_var+x}" ]]; then
        # shellcheck disable=SC2163  # eval required: _line contains "KEY=VALUE" or "export KEY=VALUE"
        eval "${_line}"
      fi
    else
      printf '%s\n' "[WARN] Ignoring unsupported line in .cgw.conf: ${_line}" >&2
    fi
  done <"${_CGW_CONF}"
  unset _line _cgw_var
fi

# ============================================================================
# DEFAULTS (applied only if still unset after env + config)
# ============================================================================

# --- Branch names ---
CGW_SOURCE_BRANCH="${CGW_SOURCE_BRANCH:-development}"
CGW_TARGET_BRANCH="${CGW_TARGET_BRANCH:-main}"

# --- Remote name ---
# Override with CGW_REMOTE=upstream (or any remote name) for fork-based workflows.
CGW_REMOTE="${CGW_REMOTE:-origin}"

# --- Local-only files (space-separated; trailing / denotes a directory) ---
# These files are never committed. configure.sh auto-detects project-specific ones.
CGW_LOCAL_FILES="${CGW_LOCAL_FILES:-CLAUDE.md MEMORY.md .claude/ logs/}"

# --- Commit message prefixes ---
# Standard conventional commit prefixes (always included):
_CGW_BASE_PREFIXES="feat|fix|docs|chore|test|refactor|style|perf"
# Project-specific extras (pipe-separated, e.g. "cuda|tensorrt"):
CGW_EXTRA_PREFIXES="${CGW_EXTRA_PREFIXES:-}"
if [[ -n "${CGW_EXTRA_PREFIXES}" ]]; then
  CGW_ALL_PREFIXES="${_CGW_BASE_PREFIXES}|${CGW_EXTRA_PREFIXES}"
else
  CGW_ALL_PREFIXES="${_CGW_BASE_PREFIXES}"
fi
export CGW_ALL_PREFIXES # consumed by commit_enhanced.sh (cross-file, not detectable by shellcheck)

# --- Lint configuration ---
# Set CGW_LINT_CMD="" to disable lint checks entirely (e.g. non-Python projects
# that haven't configured a linter yet).
# Use +x (not :-) to distinguish "unset" from "explicitly set to empty string".
[[ -z "${CGW_LINT_CMD+x}" ]] && CGW_LINT_CMD="ruff"
[[ -z "${CGW_LINT_CHECK_ARGS+x}" ]] && CGW_LINT_CHECK_ARGS="check ."
[[ -z "${CGW_LINT_FIX_ARGS+x}" ]] && CGW_LINT_FIX_ARGS="check --fix ."
[[ -z "${CGW_LINT_EXCLUDES+x}" ]] && CGW_LINT_EXCLUDES="--extend-exclude logs --extend-exclude .venv"

# Set CGW_FORMAT_CMD="" to disable formatting checks.
# Use +x (not :-) to distinguish "unset" from "explicitly set to empty string".
[[ -z "${CGW_FORMAT_CMD+x}" ]] && CGW_FORMAT_CMD="ruff"
[[ -z "${CGW_FORMAT_CHECK_ARGS+x}" ]] && CGW_FORMAT_CHECK_ARGS="format --check ."
[[ -z "${CGW_FORMAT_FIX_ARGS+x}" ]] && CGW_FORMAT_FIX_ARGS="format ."
[[ -z "${CGW_FORMAT_EXCLUDES+x}" ]] && CGW_FORMAT_EXCLUDES="--exclude logs --exclude .venv"

# Set CGW_MARKDOWNLINT_CMD to enable a dedicated markdown lint step.
# Empty (default) = markdown lint step skipped. Example: "markdownlint-cli2"
CGW_MARKDOWNLINT_CMD="${CGW_MARKDOWNLINT_CMD:-}"
CGW_MARKDOWNLINT_ARGS="${CGW_MARKDOWNLINT_ARGS:-**/*.md !CLAUDE.md !MEMORY.md}"

# --- Modified-only lint file extensions ---
# Space-separated glob patterns used by check_lint.sh / fix_lint.sh --modified-only.
# Default matches Python files. Override for other languages (e.g. "*.js *.ts" or "*.go").
[[ -z "${CGW_LINT_EXTENSIONS+x}" ]] && CGW_LINT_EXTENSIONS="*.py"

# --- Merge conflict style (merge_with_validation.sh) ---
# Set to "diff3" to show the base version in conflict markers (Pro Git recommended).
# Empty = git default (two-way markers).
CGW_MERGE_CONFLICT_STYLE="${CGW_MERGE_CONFLICT_STYLE:-}"

# --- Merge whitespace handling (merge_with_validation.sh) ---
# Set to "1" to add -Xignore-space-change to the merge command.
# Prevents false conflicts caused by whitespace-only differences.
CGW_MERGE_IGNORE_WHITESPACE="${CGW_MERGE_IGNORE_WHITESPACE:-0}"

# --- Docs CI validation (merge_with_validation.sh) ---
# Extended regex for allowed doc filenames. Empty = skip validation entirely.
# Example: "^(README\.md|.*_GUIDE\.md|.*_REFERENCE\.md)$"
CGW_DOCS_PATTERN="${CGW_DOCS_PATTERN:-}"

# --- Dev-only file exclusions for cherry-pick warnings ---
# Space-separated paths. Empty = no warning. Example: "tests/ pytest.ini"
CGW_DEV_ONLY_FILES="${CGW_DEV_ONLY_FILES:-}"

# --- Tests directory cleanup on target branch ---
# 0 = disabled (default), 1 = remove tests/ from target if gitignored
CGW_CLEANUP_TESTS="${CGW_CLEANUP_TESTS:-0}"

# --- Force-push protected branches (space-separated) ---
# Branches requiring explicit --force flag + confirmation for force-push.
CGW_PROTECTED_BRANCHES="${CGW_PROTECTED_BRANCHES:-${CGW_TARGET_BRANCH}}"

# --- Merge mode ---
# "direct": merge locally via merge_with_validation.sh (default, no PR required)
# "pr":     create a GitHub PR via create_pr.sh (triggers Charlie CI + GitHub Actions)
CGW_MERGE_MODE="${CGW_MERGE_MODE:-direct}"

# ============================================================================
# BACKWARD COMPATIBILITY
# ============================================================================
# Legacy CLAUDE_GIT_* env vars are mapped to CGW_* equivalents.

[[ "${CLAUDE_GIT_NON_INTERACTIVE:-0}" == "1" ]] && CGW_NON_INTERACTIVE=1
[[ "${CLAUDE_GIT_NO_VENV:-0}" == "1" ]] && CGW_NO_VENV=1
[[ "${CLAUDE_GIT_STAGED_ONLY:-0}" == "1" ]] && CGW_STAGED_ONLY=1

CGW_NON_INTERACTIVE="${CGW_NON_INTERACTIVE:-0}"
CGW_NO_VENV="${CGW_NO_VENV:-0}"
CGW_STAGED_ONLY="${CGW_STAGED_ONLY:-0}"
