#!/usr/bin/env bash
# setup_attributes.sh - Generate .gitattributes for binary and project-specific files
# Purpose: Configure git to handle binary files correctly (no diff, no merge conflicts)
#          and set text file line-ending normalization. Supports Python, TouchDesigner,
#          GLSL, and common asset types.
# Usage: ./scripts/git/setup_attributes.sh [OPTIONS]
#
# Globals:
#   SCRIPT_DIR   - Directory containing this script
#   PROJECT_ROOT - Auto-detected git repo root (set by _config.sh)
# Arguments:
#   --dry-run    Show what would be written without modifying .gitattributes
#   --force      Overwrite existing .gitattributes without prompting
#   -h, --help   Show help
# Returns:
#   0 on success, 1 on failure

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_common.sh"

# detect_project_types - Scan PROJECT_ROOT for known project type indicators.
# Sets global flags: has_python, has_touchdesigner, has_glsl, has_rust, has_js, has_go
detect_project_types() {
  has_python=0
  has_touchdesigner=0
  has_glsl=0
  has_rust=0
  has_js=0
  has_go=0

  # Python
  [[ -f "${PROJECT_ROOT}/pyproject.toml" ]] && has_python=1
  [[ -f "${PROJECT_ROOT}/setup.py" ]] && has_python=1
  [[ -f "${PROJECT_ROOT}/requirements.txt" ]] && has_python=1
  [[ -n "$(find "${PROJECT_ROOT}" -maxdepth 3 -name "*.py" -print -quit 2>/dev/null)" ]] && has_python=1

  # TouchDesigner
  [[ -n "$(find "${PROJECT_ROOT}" -maxdepth 3 \( -name "*.toe" -o -name "*.tox" \) -print -quit 2>/dev/null)" ]] && has_touchdesigner=1

  # GLSL / shaders
  [[ -n "$(find "${PROJECT_ROOT}" -maxdepth 5 \( -name "*.glsl" -o -name "*.vert" -o -name "*.frag" -o -name "*.comp" -o -name "*.geom" -o -name "*.spv" \) -print -quit 2>/dev/null)" ]] && has_glsl=1

  # Rust
  [[ -f "${PROJECT_ROOT}/Cargo.toml" ]] && has_rust=1

  # JavaScript / TypeScript
  [[ -f "${PROJECT_ROOT}/package.json" ]] && has_js=1

  # Go
  [[ -f "${PROJECT_ROOT}/go.mod" ]] && has_go=1
}

# build_attributes - Build .gitattributes content based on detected project types.
# Uses has_python, has_touchdesigner, has_glsl, has_js, has_rust, has_go globals.
build_attributes() {

  cat <<'EOF'
# .gitattributes -- generated by claude-git-workflow setup_attributes.sh
# Controls line endings (text files) and merge strategy (binary files).

# ============================================================================
# TEXT FILES -- normalize line endings to LF in repo, native on checkout
# ============================================================================

* text=auto

# Shell scripts always LF
*.sh text eol=lf
*.bash text eol=lf

# Config and data files
*.json text eol=lf
*.yaml text eol=lf
*.yml text eol=lf
*.toml text eol=lf
*.ini text eol=lf
*.cfg text eol=lf
*.conf text eol=lf
*.md text eol=lf
*.txt text eol=lf
*.csv text eol=lf

EOF

  # Python-specific
  if [[ "${has_python}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# PYTHON
# ============================================================================

*.py text eol=lf diff=python
*.pyx text eol=lf
*.pxd text eol=lf

# Python binary artifacts -- do not diff or merge
*.pyc binary
*.pyd binary
*.pyo binary
*.so binary
*.egg binary
*.whl binary

# Python build artifacts -- exclude from archives
*.egg-info/ export-ignore
dist/ export-ignore
build/ export-ignore
__pycache__/ export-ignore

EOF
  fi

  # TouchDesigner-specific
  if [[ "${has_touchdesigner}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# TOUCHDESIGNER
# ============================================================================

# .toe (project files) and .tox (components) are SQLite databases -- binary
*.toe binary
*.tox binary

# TouchDesigner auto-backups -- exclude from archives
*.toe.bak export-ignore
Backup/ export-ignore

EOF
  fi

  # GLSL / shader-specific
  if [[ "${has_glsl}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# GLSL / SHADERS
# ============================================================================

# Source shader files -- text, always LF
*.glsl text eol=lf
*.vert text eol=lf
*.frag text eol=lf
*.geom text eol=lf
*.tesc text eol=lf
*.tese text eol=lf
*.comp text eol=lf
*.rgen text eol=lf
*.rmiss text eol=lf
*.rchit text eol=lf

# Compiled SPIR-V -- binary, do not diff or merge
*.spv binary

EOF
  fi

  # JavaScript/TypeScript
  if [[ "${has_js}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# JAVASCRIPT / TYPESCRIPT
# ============================================================================

*.js text eol=lf
*.ts text eol=lf
*.jsx text eol=lf
*.tsx text eol=lf
*.mjs text eol=lf
*.cjs text eol=lf
*.vue text eol=lf

# Build output -- exclude from archives
node_modules/ export-ignore
dist/ export-ignore
build/ export-ignore

EOF
  fi

  # Go
  if [[ "${has_go}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# GO
# ============================================================================

*.go text eol=lf diff=golang

EOF
  fi

  # Rust
  if [[ "${has_rust}" -eq 1 ]]; then
    cat <<'EOF'
# ============================================================================
# RUST
# ============================================================================

*.rs text eol=lf diff=rust
Cargo.lock text eol=lf

EOF
  fi

  # Common binary assets (always added)
  cat <<'EOF'
# ============================================================================
# COMMON BINARY ASSETS
# ============================================================================

# Images
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.bmp binary
*.tga binary
*.tiff binary
*.webp binary
*.ico binary
*.psd binary

# HDR / EXR (common in TD/GLSL projects)
*.exr binary
*.hdr binary

# Audio
*.wav binary
*.mp3 binary
*.ogg binary
*.flac binary
*.aiff binary

# Video
*.mp4 binary
*.mov binary
*.avi binary
*.mkv binary

# Fonts
*.ttf binary
*.otf binary
*.woff binary
*.woff2 binary

# 3D / scene files
*.fbx binary
*.obj text eol=lf
*.mtl text eol=lf
*.blend binary
*.glb binary

# Archives
*.zip binary
*.tar binary
*.gz binary
*.7z binary

# PDF
*.pdf binary

# ============================================================================
# EXPORT ARCHIVE EXCLUSIONS
# ============================================================================

# Never include in git archive exports (e.g. GitHub source tarballs)
.gitignore export-ignore
.gitattributes export-ignore
.github/ export-ignore
tests/ export-ignore
*.log export-ignore
logs/ export-ignore

EOF
}

main() {
  local dry_run=0
  local force=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --help | -h)
        echo "Usage: ./scripts/git/setup_attributes.sh [OPTIONS]"
        echo ""
        echo "Generate .gitattributes for the project, configuring:"
        echo "  - Line ending normalization (text files -> LF in repo)"
        echo "  - Binary file handling (no diff, no merge conflicts)"
        echo "  - Export-ignore for build artifacts and CI files"
        echo ""
        echo "Auto-detects: Python, TouchDesigner (.toe/.tox), GLSL shaders,"
        echo "              JavaScript/TypeScript, Go, Rust"
        echo ""
        echo "Options:"
        echo "  --dry-run   Show output without writing to .gitattributes"
        echo "  --force     Overwrite existing .gitattributes without prompting"
        echo "  -h, --help  Show this help"
        exit 0
        ;;
      --dry-run) dry_run=1 ;;
      --force) force=1 ;;
      *)
        echo "[ERROR] Unknown flag: $1" >&2
        exit 1
        ;;
    esac
    shift
  done

  cd "${PROJECT_ROOT}" || {
    err "Cannot find project root"
    exit 1
  }

  echo "=== Setup .gitattributes ==="
  echo ""

  # Detect project types
  local has_python has_touchdesigner has_glsl has_rust has_js has_go
  detect_project_types

  echo "Detected project types:"
  [[ "${has_python}" -eq 1 ]] && echo "  [OK] Python"
  [[ "${has_touchdesigner}" -eq 1 ]] && echo "  [OK] TouchDesigner"
  [[ "${has_glsl}" -eq 1 ]] && echo "  [OK] GLSL/shaders"
  [[ "${has_js}" -eq 1 ]] && echo "  [OK] JavaScript/TypeScript"
  [[ "${has_go}" -eq 1 ]] && echo "  [OK] Go"
  [[ "${has_rust}" -eq 1 ]] && echo "  [OK] Rust"
  echo ""

  local attr_content
  attr_content=$(build_attributes)

  if [[ ${dry_run} -eq 1 ]]; then
    echo "--- Dry run: would write to .gitattributes ---"
    echo ""
    echo "${attr_content}"
    echo ""
    echo "--- End dry run ---"
    exit 0
  fi

  # Check existing file
  if [[ -f "${PROJECT_ROOT}/.gitattributes" ]] && [[ ${force} -eq 0 ]]; then
    echo "[!] .gitattributes already exists."
    echo ""
    read -r -p "Overwrite? (yes/no) [no]: " answer
    case "$(echo "${answer}" | tr '[:upper:]' '[:lower:]')" in
      y | yes) ;;
      *)
        echo "Aborted -- .gitattributes not modified."
        exit 0
        ;;
    esac
  fi

  echo "${attr_content}" >"${PROJECT_ROOT}/.gitattributes"
  echo "[OK] Written: ${PROJECT_ROOT}/.gitattributes"
  echo ""
  echo "Next steps:"
  echo "  git add .gitattributes"
  echo "  git commit -m 'chore: configure .gitattributes for binary and text files'"
  echo ""
  echo "If you have existing binary files already tracked, renormalize them:"
  echo "  git add --renormalize ."
  echo "  git commit -m 'chore: renormalize line endings'"
}

main "$@"
